language: php

php:
  - 7.1
  - 7.2

env:
    matrix:
        - COMPOSER_FLAGS=""
        - COMPOSER_FLAGS="--prefer-lowest"

cache:
    directories:
        - $HOME/.composer/cache/files

notifications:
    email: false

install:
    - composer self-update
    - composer update $COMPOSER_FLAGS

script: make test
